# Generated by Django 5.1.5 on 2025-01-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
